api:
  version: 1.0.0
  title: Proyecto microservicio cliente
  basePackage: com.example.factory.client
  description: Automated JSON API documentation for API's built with Spring
  terms: https://
server:
  servlet:
    context-path: /client
  port : 8080
# ===============================
# = DATA SOURCE MYSQL
# ===============================

#configuracion mysql basica

spring:
  datasource:
    #url: jdbc:postgresql://10.19.34.188/zee_db
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/factory
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate.ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5Dialect

    # swagger-ui custom path
springdoc:
  api-docs:
    path: /api-docs